# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1305ad168aa547aaa63254c06d0c4d766c076fa7d74d2e6fe839c84e5394ce46a9b9e3132ad62fb435066bd6bee3b5b1c21234b0bb5cbc6227a5fcfbfd1f7643

test:
  secret_key_base: aaaf2ca77dd8693344dd384b5d8d23ebe859c8b90081207d24ac8908db621cfabb16027b4e66c0473b86e8561cd3c7ffffbc203ae3b891549587a9b5c0dbf5ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
